name: ReminecraftDevmode
version: 1.1.0
main: org.reminecraft.devmode.ReminecraftDevmode
api-version: '1.21'
description: Anti-bot, MOTD, chat filter, rate limiter, group messages, plugin manager

commands:
  devmode:
    description: Devmode admin commands
    usage: /devmode <reload|plugin|filter|unban>
    permission: reminecraftdevmode.admin
  superlist:
    description: Kelola superlist dan lihat semua player yang pernah join
    usage: /superlist [add|remove <player>] [page <n>]

permissions:
  reminecraftdevmode.admin:
    description: Akses penuh ke devmode
    default: op
