#Minecraft server properties
#Thu Jun 18 22:54:52 WIB 2026
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=100000
max-players=250
max-tick-time=60000
max-world-size=29999984
motd=Reminecraft - Java + Bedrock
network-compression-threshold=1024
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=http\://localhost\:8080/reminecraft-java.zip
resource-pack-id=4a5b6c7d-8e9f-0a1b-2c3d-4e5f6a7b8c9d
resource-pack-prompt={"text":"Reminecraft - Vulkan Optimized Pack","color":"aqua"}
resource-pack-sha1=6f63ed1a24ac15e0a21fa6124997be8a599261d7
server-ip=0.0.0.0
server-name=Unknown Server
server-port=25565
simulation-distance=4
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=5
white-list=false
﻿\#Minecraft=server properties
